#############################################################################
# Makefile for building: EAICar-vision
# Generated by qmake (3.0) (Qt 5.6.0)
# Project:  EAICar-vision.pro
# Template: app
# Command: /opt/Qt5.6.0/5.6/gcc_64/bin/qmake -o Makefile EAICar-vision.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -std=gnu++0x -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I/usr/local/include -I/usr/local/include/opencv -I/usr/local/include/opencv2 -I/opt/Qt5.6.0/5.6/gcc_64/include -I/opt/Qt5.6.0/5.6/gcc_64/include/QtNetwork -I/opt/Qt5.6.0/5.6/gcc_64/include/QtCore -I. -I/opt/Qt5.6.0/5.6/gcc_64/mkspecs/linux-g++
QMAKE         = /opt/Qt5.6.0/5.6/gcc_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = EAICar-vision1.0.0
DISTDIR = /home/xcy/QTProject/EAIcar_vison2-master/.tmp/EAICar-vision1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-z,origin -Wl,-rpath,\$$ORIGIN -Wl,-rpath,/opt/Qt5.6.0/5.6/gcc_64/lib
LIBS          = $(SUBLIBS) /usr/local/lib/libopencv_*.so -L/opt/Qt5.6.0/5.6/gcc_64/lib -lQt5Network -lQt5Core -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		dector.cpp \
		socketclient.cpp moc_socketclient.cpp
OBJECTS       = main.o \
		dector.o \
		socketclient.o \
		moc_socketclient.o
DIST          = /opt/Qt5.6.0/5.6/gcc_64/mkspecs/features/spec_pre.prf \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/common/unix.conf \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/common/linux.conf \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/common/sanitize.conf \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/common/gcc-base.conf \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/common/gcc-base-unix.conf \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/common/g++-base.conf \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/common/g++-unix.conf \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/qconfig.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_3drender.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_core.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_help.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_labscontrols_private.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_labstemplates_private.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_location.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_network.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_script.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_serialbus.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/features/qt_functions.prf \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/features/qt_config.prf \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/linux-g++/qmake.conf \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/features/spec_post.prf \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/features/exclusive_builds.prf \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/features/default_pre.prf \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/features/resolve_config.prf \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/features/default_post.prf \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/features/warn_on.prf \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/features/qt.prf \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/features/resources.prf \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/features/moc.prf \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/features/unix/thread.prf \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/features/testcase_targets.prf \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/features/exceptions.prf \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/features/yacc.prf \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/features/lex.prf \
		EAICar-vision.pro dector.h \
		socketclient.h main.cpp \
		dector.cpp \
		socketclient.cpp
QMAKE_TARGET  = EAICar-vision
DESTDIR       = 
TARGET        = EAICar-vision


first: all
####### Build rules

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: EAICar-vision.pro /opt/Qt5.6.0/5.6/gcc_64/mkspecs/linux-g++/qmake.conf /opt/Qt5.6.0/5.6/gcc_64/mkspecs/features/spec_pre.prf \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/common/unix.conf \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/common/linux.conf \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/common/sanitize.conf \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/common/gcc-base.conf \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/common/gcc-base-unix.conf \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/common/g++-base.conf \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/common/g++-unix.conf \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/qconfig.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_3drender.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_core.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_help.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_labscontrols_private.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_labstemplates_private.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_location.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_network.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_script.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_serialbus.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/features/qt_functions.prf \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/features/qt_config.prf \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/linux-g++/qmake.conf \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/features/spec_post.prf \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/features/exclusive_builds.prf \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/features/default_pre.prf \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/features/resolve_config.prf \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/features/default_post.prf \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/features/warn_on.prf \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/features/qt.prf \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/features/resources.prf \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/features/moc.prf \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/features/unix/thread.prf \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/features/testcase_targets.prf \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/features/exceptions.prf \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/features/yacc.prf \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/features/lex.prf \
		EAICar-vision.pro \
		/opt/Qt5.6.0/5.6/gcc_64/lib/libQt5Network.prl \
		/opt/Qt5.6.0/5.6/gcc_64/lib/libQt5Core.prl
	$(QMAKE) -o Makefile EAICar-vision.pro
/opt/Qt5.6.0/5.6/gcc_64/mkspecs/features/spec_pre.prf:
/opt/Qt5.6.0/5.6/gcc_64/mkspecs/common/unix.conf:
/opt/Qt5.6.0/5.6/gcc_64/mkspecs/common/linux.conf:
/opt/Qt5.6.0/5.6/gcc_64/mkspecs/common/sanitize.conf:
/opt/Qt5.6.0/5.6/gcc_64/mkspecs/common/gcc-base.conf:
/opt/Qt5.6.0/5.6/gcc_64/mkspecs/common/gcc-base-unix.conf:
/opt/Qt5.6.0/5.6/gcc_64/mkspecs/common/g++-base.conf:
/opt/Qt5.6.0/5.6/gcc_64/mkspecs/common/g++-unix.conf:
/opt/Qt5.6.0/5.6/gcc_64/mkspecs/qconfig.pri:
/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_3dcore.pri:
/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri:
/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_3dinput.pri:
/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri:
/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri:
/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_3dquick.pri:
/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri:
/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri:
/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri:
/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_3drender.pri:
/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri:
/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri:
/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri:
/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri:
/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_core.pri:
/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_core_private.pri:
/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri:
/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_designer.pri:
/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_designer_private.pri:
/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri:
/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_gui.pri:
/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_gui_private.pri:
/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_help.pri:
/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_help_private.pri:
/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_labscontrols_private.pri:
/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_labstemplates_private.pri:
/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_location.pri:
/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_location_private.pri:
/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri:
/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_network.pri:
/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_network_private.pri:
/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_nfc.pri:
/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri:
/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri:
/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri:
/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_positioning.pri:
/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri:
/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri:
/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_qml.pri:
/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_qml_private.pri:
/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri:
/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_quick.pri:
/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_quick_private.pri:
/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri:
/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_script.pri:
/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_script_private.pri:
/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_scripttools.pri:
/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri:
/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_sensors.pri:
/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri:
/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_serialbus.pri:
/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri:
/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_serialport.pri:
/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri:
/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_sql.pri:
/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_sql_private.pri:
/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_svg.pri:
/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_svg_private.pri:
/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri:
/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri:
/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri:
/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_webchannel.pri:
/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri:
/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_webengine.pri:
/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri:
/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri:
/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_websockets.pri:
/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri:
/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_webview.pri:
/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_webview_private.pri:
/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri:
/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_x11extras.pri:
/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri:
/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_xml.pri:
/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_xml_private.pri:
/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
/opt/Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/opt/Qt5.6.0/5.6/gcc_64/mkspecs/features/qt_functions.prf:
/opt/Qt5.6.0/5.6/gcc_64/mkspecs/features/qt_config.prf:
/opt/Qt5.6.0/5.6/gcc_64/mkspecs/linux-g++/qmake.conf:
/opt/Qt5.6.0/5.6/gcc_64/mkspecs/features/spec_post.prf:
/opt/Qt5.6.0/5.6/gcc_64/mkspecs/features/exclusive_builds.prf:
/opt/Qt5.6.0/5.6/gcc_64/mkspecs/features/default_pre.prf:
/opt/Qt5.6.0/5.6/gcc_64/mkspecs/features/resolve_config.prf:
/opt/Qt5.6.0/5.6/gcc_64/mkspecs/features/default_post.prf:
/opt/Qt5.6.0/5.6/gcc_64/mkspecs/features/warn_on.prf:
/opt/Qt5.6.0/5.6/gcc_64/mkspecs/features/qt.prf:
/opt/Qt5.6.0/5.6/gcc_64/mkspecs/features/resources.prf:
/opt/Qt5.6.0/5.6/gcc_64/mkspecs/features/moc.prf:
/opt/Qt5.6.0/5.6/gcc_64/mkspecs/features/unix/thread.prf:
/opt/Qt5.6.0/5.6/gcc_64/mkspecs/features/testcase_targets.prf:
/opt/Qt5.6.0/5.6/gcc_64/mkspecs/features/exceptions.prf:
/opt/Qt5.6.0/5.6/gcc_64/mkspecs/features/yacc.prf:
/opt/Qt5.6.0/5.6/gcc_64/mkspecs/features/lex.prf:
EAICar-vision.pro:
/opt/Qt5.6.0/5.6/gcc_64/lib/libQt5Network.prl:
/opt/Qt5.6.0/5.6/gcc_64/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile EAICar-vision.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents dector.h socketclient.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp dector.cpp socketclient.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: moc_socketclient.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_socketclient.cpp
moc_socketclient.cpp: /opt/Qt5.6.0/5.6/gcc_64/include/QtNetwork/QTcpSocket \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtNetwork/qtcpsocket.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtNetwork/qabstractsocket.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qiodevice.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qglobal.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qconfig.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qfeatures.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qsystemdetection.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qprocessordetection.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qcompilerdetection.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qtypeinfo.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qtypetraits.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qisenum.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qsysinfo.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qlogging.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qflags.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qatomic.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qbasicatomic.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qgenericatomic.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qatomic_cxx11.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qatomic_gcc.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qatomic_msvc.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qatomic_armv7.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qatomic_armv6.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qatomic_armv5.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qatomic_ia64.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qatomic_x86.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qatomic_unix.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qglobalstatic.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qmutex.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qnumeric.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qversiontagging.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qobject.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qobjectdefs.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qnamespace.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qstring.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qchar.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qbytearray.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qrefcount.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qarraydata.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qstringbuilder.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qlist.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qalgorithms.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qiterator.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qhashfunctions.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qpair.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qbytearraylist.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qstringlist.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qregexp.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qstringmatcher.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qcoreevent.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qscopedpointer.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qmetatype.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qvarlengtharray.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qcontainerfwd.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qobject_impl.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qdebug.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qhash.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qmap.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qtextstream.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qlocale.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qvariant.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qshareddata.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qvector.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qpoint.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qset.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qcontiguouscache.h \
		socketclient.h
	/opt/Qt5.6.0/5.6/gcc_64/bin/moc $(DEFINES) -I/opt/Qt5.6.0/5.6/gcc_64/mkspecs/linux-g++ -I/home/xcy/QTProject/EAIcar_vison2-master -I/usr/local/include -I/usr/local/include/opencv -I/usr/local/include/opencv2 -I/opt/Qt5.6.0/5.6/gcc_64/include -I/opt/Qt5.6.0/5.6/gcc_64/include/QtNetwork -I/opt/Qt5.6.0/5.6/gcc_64/include/QtCore socketclient.h -o moc_socketclient.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

main.o: main.cpp dector.h \
		/usr/local/include/opencv2/opencv.hpp \
		/usr/local/include/opencv2/opencv_modules.hpp \
		/usr/local/include/opencv2/core.hpp \
		/usr/local/include/opencv2/core/cvdef.h \
		/usr/local/include/opencv2/cvconfig.h \
		/usr/local/include/opencv2/core/hal/interface.h \
		/usr/local/include/opencv2/core/cv_cpu_dispatch.h \
		/usr/local/include/opencv2/core/cv_cpu_helper.h \
		/usr/local/include/opencv2/core/version.hpp \
		/usr/local/include/opencv2/core/base.hpp \
		/usr/local/include/opencv2/core/cvstd.hpp \
		/usr/local/include/opencv2/core/ptr.inl.hpp \
		/usr/local/include/opencv2/core/neon_utils.hpp \
		/usr/local/include/opencv2/core/traits.hpp \
		/usr/local/include/opencv2/core/matx.hpp \
		/usr/local/include/opencv2/core/saturate.hpp \
		/usr/local/include/opencv2/core/fast_math.hpp \
		/usr/local/include/opencv2/core/types.hpp \
		/usr/local/include/opencv2/core/mat.hpp \
		/usr/local/include/opencv2/core/bufferpool.hpp \
		/usr/local/include/opencv2/core/mat.inl.hpp \
		/usr/local/include/opencv2/core/persistence.hpp \
		/usr/local/include/opencv2/core/operations.hpp \
		/usr/local/include/opencv2/core/cvstd.inl.hpp \
		/usr/local/include/opencv2/core/utility.hpp \
		/usr/local/include/opencv2/core/core_c.h \
		/usr/local/include/opencv2/core/types_c.h \
		/usr/local/include/opencv2/core/optim.hpp \
		/usr/local/include/opencv2/core/ovx.hpp \
		/usr/local/include/opencv2/calib3d.hpp \
		/usr/local/include/opencv2/features2d.hpp \
		/usr/local/include/opencv2/flann/miniflann.hpp \
		/usr/local/include/opencv2/flann/defines.h \
		/usr/local/include/opencv2/flann/config.h \
		/usr/local/include/opencv2/core/affine.hpp \
		/usr/local/include/opencv2/calib3d/calib3d_c.h \
		/usr/local/include/opencv2/flann.hpp \
		/usr/local/include/opencv2/flann/flann_base.hpp \
		/usr/local/include/opencv2/flann/general.h \
		/usr/local/include/opencv2/flann/matrix.h \
		/usr/local/include/opencv2/flann/params.h \
		/usr/local/include/opencv2/flann/any.h \
		/usr/local/include/opencv2/flann/saving.h \
		/usr/local/include/opencv2/flann/nn_index.h \
		/usr/local/include/opencv2/flann/result_set.h \
		/usr/local/include/opencv2/flann/all_indices.h \
		/usr/local/include/opencv2/flann/kdtree_index.h \
		/usr/local/include/opencv2/flann/dynamic_bitset.h \
		/usr/local/include/opencv2/flann/dist.h \
		/usr/local/include/opencv2/flann/heap.h \
		/usr/local/include/opencv2/flann/allocator.h \
		/usr/local/include/opencv2/flann/random.h \
		/usr/local/include/opencv2/flann/kdtree_single_index.h \
		/usr/local/include/opencv2/flann/kmeans_index.h \
		/usr/local/include/opencv2/flann/logger.h \
		/usr/local/include/opencv2/flann/composite_index.h \
		/usr/local/include/opencv2/flann/linear_index.h \
		/usr/local/include/opencv2/flann/hierarchical_clustering_index.h \
		/usr/local/include/opencv2/flann/lsh_index.h \
		/usr/local/include/opencv2/flann/lsh_table.h \
		/usr/local/include/opencv2/flann/autotuned_index.h \
		/usr/local/include/opencv2/flann/ground_truth.h \
		/usr/local/include/opencv2/flann/index_testing.h \
		/usr/local/include/opencv2/flann/timer.h \
		/usr/local/include/opencv2/flann/sampling.h \
		/usr/local/include/opencv2/highgui.hpp \
		/usr/local/include/opencv2/imgcodecs.hpp \
		/usr/local/include/opencv2/videoio.hpp \
		/usr/local/include/opencv2/highgui/highgui_c.h \
		/usr/local/include/opencv2/imgproc/imgproc_c.h \
		/usr/local/include/opencv2/imgproc/types_c.h \
		/usr/local/include/opencv2/imgcodecs/imgcodecs_c.h \
		/usr/local/include/opencv2/videoio/videoio_c.h \
		/usr/local/include/opencv2/imgproc.hpp \
		/usr/local/include/opencv2/ml.hpp \
		/usr/local/include/opencv2/objdetect.hpp \
		/usr/local/include/opencv2/objdetect/detection_based_tracker.hpp \
		/usr/local/include/opencv2/objdetect/objdetect_c.h \
		/usr/local/include/opencv2/photo.hpp \
		/usr/local/include/opencv2/photo/photo_c.h \
		/usr/local/include/opencv2/shape.hpp \
		/usr/local/include/opencv2/shape/emdL1.hpp \
		/usr/local/include/opencv2/shape/shape_transformer.hpp \
		/usr/local/include/opencv2/shape/hist_cost.hpp \
		/usr/local/include/opencv2/shape/shape_distance.hpp \
		/usr/local/include/opencv2/stitching.hpp \
		/usr/local/include/opencv2/stitching/warpers.hpp \
		/usr/local/include/opencv2/stitching/detail/warpers.hpp \
		/usr/local/include/opencv2/core/cuda.hpp \
		/usr/local/include/opencv2/core/cuda_types.hpp \
		/usr/local/include/opencv2/core/cuda.inl.hpp \
		/usr/local/include/opencv2/stitching/detail/warpers_inl.hpp \
		/usr/local/include/opencv2/stitching/detail/matchers.hpp \
		/usr/local/include/opencv2/stitching/detail/motion_estimators.hpp \
		/usr/local/include/opencv2/stitching/detail/util.hpp \
		/usr/local/include/opencv2/stitching/detail/util_inl.hpp \
		/usr/local/include/opencv2/stitching/detail/camera.hpp \
		/usr/local/include/opencv2/stitching/detail/exposure_compensate.hpp \
		/usr/local/include/opencv2/stitching/detail/seam_finders.hpp \
		/usr/local/include/opencv2/stitching/detail/blenders.hpp \
		/usr/local/include/opencv2/superres.hpp \
		/usr/local/include/opencv2/superres/optical_flow.hpp \
		/usr/local/include/opencv2/video.hpp \
		/usr/local/include/opencv2/video/tracking.hpp \
		/usr/local/include/opencv2/video/background_segm.hpp \
		/usr/local/include/opencv2/video/tracking_c.h \
		/usr/local/include/opencv2/videostab.hpp \
		/usr/local/include/opencv2/videostab/stabilizer.hpp \
		/usr/local/include/opencv2/videostab/global_motion.hpp \
		/usr/local/include/opencv2/videostab/optical_flow.hpp \
		/usr/local/include/opencv2/videostab/motion_core.hpp \
		/usr/local/include/opencv2/videostab/outlier_rejection.hpp \
		/usr/local/include/opencv2/videostab/motion_stabilizing.hpp \
		/usr/local/include/opencv2/videostab/frame_source.hpp \
		/usr/local/include/opencv2/videostab/log.hpp \
		/usr/local/include/opencv2/videostab/inpainting.hpp \
		/usr/local/include/opencv2/videostab/fast_marching.hpp \
		/usr/local/include/opencv2/videostab/fast_marching_inl.hpp \
		/usr/local/include/opencv2/videostab/deblurring.hpp \
		/usr/local/include/opencv2/videostab/wobble_suppression.hpp \
		/usr/local/include/opencv2/videostab/ring_buffer.hpp \
		/usr/local/include/opencv2/viz.hpp \
		/usr/local/include/opencv2/viz/types.hpp \
		/usr/local/include/opencv2/viz/widgets.hpp \
		/usr/local/include/opencv2/viz/viz3d.hpp \
		/usr/local/include/opencv2/viz/vizcore.hpp \
		/usr/local/include/opencv2/core/core.hpp \
		/usr/local/include/opencv2/highgui/highgui.hpp \
		/usr/local/include/opencv2/imgproc/imgproc.hpp \
		socketclient.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtNetwork/QTcpSocket \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtNetwork/qtcpsocket.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtNetwork/qabstractsocket.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qiodevice.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qglobal.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qconfig.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qfeatures.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qsystemdetection.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qprocessordetection.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qcompilerdetection.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qtypeinfo.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qtypetraits.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qisenum.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qsysinfo.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qlogging.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qflags.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qatomic.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qbasicatomic.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qgenericatomic.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qatomic_cxx11.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qatomic_gcc.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qatomic_msvc.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qatomic_armv7.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qatomic_armv6.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qatomic_armv5.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qatomic_ia64.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qatomic_x86.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qatomic_unix.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qglobalstatic.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qmutex.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qnumeric.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qversiontagging.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qobject.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qobjectdefs.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qnamespace.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qstring.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qchar.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qbytearray.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qrefcount.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qarraydata.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qstringbuilder.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qlist.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qalgorithms.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qiterator.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qhashfunctions.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qpair.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qbytearraylist.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qstringlist.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qregexp.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qstringmatcher.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qcoreevent.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qscopedpointer.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qmetatype.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qvarlengtharray.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qcontainerfwd.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qobject_impl.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qdebug.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qhash.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qmap.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qtextstream.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qlocale.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qvariant.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qshareddata.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qvector.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qpoint.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qset.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qcontiguouscache.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

dector.o: dector.cpp dector.h \
		/usr/local/include/opencv2/opencv.hpp \
		/usr/local/include/opencv2/opencv_modules.hpp \
		/usr/local/include/opencv2/core.hpp \
		/usr/local/include/opencv2/core/cvdef.h \
		/usr/local/include/opencv2/cvconfig.h \
		/usr/local/include/opencv2/core/hal/interface.h \
		/usr/local/include/opencv2/core/cv_cpu_dispatch.h \
		/usr/local/include/opencv2/core/cv_cpu_helper.h \
		/usr/local/include/opencv2/core/version.hpp \
		/usr/local/include/opencv2/core/base.hpp \
		/usr/local/include/opencv2/core/cvstd.hpp \
		/usr/local/include/opencv2/core/ptr.inl.hpp \
		/usr/local/include/opencv2/core/neon_utils.hpp \
		/usr/local/include/opencv2/core/traits.hpp \
		/usr/local/include/opencv2/core/matx.hpp \
		/usr/local/include/opencv2/core/saturate.hpp \
		/usr/local/include/opencv2/core/fast_math.hpp \
		/usr/local/include/opencv2/core/types.hpp \
		/usr/local/include/opencv2/core/mat.hpp \
		/usr/local/include/opencv2/core/bufferpool.hpp \
		/usr/local/include/opencv2/core/mat.inl.hpp \
		/usr/local/include/opencv2/core/persistence.hpp \
		/usr/local/include/opencv2/core/operations.hpp \
		/usr/local/include/opencv2/core/cvstd.inl.hpp \
		/usr/local/include/opencv2/core/utility.hpp \
		/usr/local/include/opencv2/core/core_c.h \
		/usr/local/include/opencv2/core/types_c.h \
		/usr/local/include/opencv2/core/optim.hpp \
		/usr/local/include/opencv2/core/ovx.hpp \
		/usr/local/include/opencv2/calib3d.hpp \
		/usr/local/include/opencv2/features2d.hpp \
		/usr/local/include/opencv2/flann/miniflann.hpp \
		/usr/local/include/opencv2/flann/defines.h \
		/usr/local/include/opencv2/flann/config.h \
		/usr/local/include/opencv2/core/affine.hpp \
		/usr/local/include/opencv2/calib3d/calib3d_c.h \
		/usr/local/include/opencv2/flann.hpp \
		/usr/local/include/opencv2/flann/flann_base.hpp \
		/usr/local/include/opencv2/flann/general.h \
		/usr/local/include/opencv2/flann/matrix.h \
		/usr/local/include/opencv2/flann/params.h \
		/usr/local/include/opencv2/flann/any.h \
		/usr/local/include/opencv2/flann/saving.h \
		/usr/local/include/opencv2/flann/nn_index.h \
		/usr/local/include/opencv2/flann/result_set.h \
		/usr/local/include/opencv2/flann/all_indices.h \
		/usr/local/include/opencv2/flann/kdtree_index.h \
		/usr/local/include/opencv2/flann/dynamic_bitset.h \
		/usr/local/include/opencv2/flann/dist.h \
		/usr/local/include/opencv2/flann/heap.h \
		/usr/local/include/opencv2/flann/allocator.h \
		/usr/local/include/opencv2/flann/random.h \
		/usr/local/include/opencv2/flann/kdtree_single_index.h \
		/usr/local/include/opencv2/flann/kmeans_index.h \
		/usr/local/include/opencv2/flann/logger.h \
		/usr/local/include/opencv2/flann/composite_index.h \
		/usr/local/include/opencv2/flann/linear_index.h \
		/usr/local/include/opencv2/flann/hierarchical_clustering_index.h \
		/usr/local/include/opencv2/flann/lsh_index.h \
		/usr/local/include/opencv2/flann/lsh_table.h \
		/usr/local/include/opencv2/flann/autotuned_index.h \
		/usr/local/include/opencv2/flann/ground_truth.h \
		/usr/local/include/opencv2/flann/index_testing.h \
		/usr/local/include/opencv2/flann/timer.h \
		/usr/local/include/opencv2/flann/sampling.h \
		/usr/local/include/opencv2/highgui.hpp \
		/usr/local/include/opencv2/imgcodecs.hpp \
		/usr/local/include/opencv2/videoio.hpp \
		/usr/local/include/opencv2/highgui/highgui_c.h \
		/usr/local/include/opencv2/imgproc/imgproc_c.h \
		/usr/local/include/opencv2/imgproc/types_c.h \
		/usr/local/include/opencv2/imgcodecs/imgcodecs_c.h \
		/usr/local/include/opencv2/videoio/videoio_c.h \
		/usr/local/include/opencv2/imgproc.hpp \
		/usr/local/include/opencv2/ml.hpp \
		/usr/local/include/opencv2/objdetect.hpp \
		/usr/local/include/opencv2/objdetect/detection_based_tracker.hpp \
		/usr/local/include/opencv2/objdetect/objdetect_c.h \
		/usr/local/include/opencv2/photo.hpp \
		/usr/local/include/opencv2/photo/photo_c.h \
		/usr/local/include/opencv2/shape.hpp \
		/usr/local/include/opencv2/shape/emdL1.hpp \
		/usr/local/include/opencv2/shape/shape_transformer.hpp \
		/usr/local/include/opencv2/shape/hist_cost.hpp \
		/usr/local/include/opencv2/shape/shape_distance.hpp \
		/usr/local/include/opencv2/stitching.hpp \
		/usr/local/include/opencv2/stitching/warpers.hpp \
		/usr/local/include/opencv2/stitching/detail/warpers.hpp \
		/usr/local/include/opencv2/core/cuda.hpp \
		/usr/local/include/opencv2/core/cuda_types.hpp \
		/usr/local/include/opencv2/core/cuda.inl.hpp \
		/usr/local/include/opencv2/stitching/detail/warpers_inl.hpp \
		/usr/local/include/opencv2/stitching/detail/matchers.hpp \
		/usr/local/include/opencv2/stitching/detail/motion_estimators.hpp \
		/usr/local/include/opencv2/stitching/detail/util.hpp \
		/usr/local/include/opencv2/stitching/detail/util_inl.hpp \
		/usr/local/include/opencv2/stitching/detail/camera.hpp \
		/usr/local/include/opencv2/stitching/detail/exposure_compensate.hpp \
		/usr/local/include/opencv2/stitching/detail/seam_finders.hpp \
		/usr/local/include/opencv2/stitching/detail/blenders.hpp \
		/usr/local/include/opencv2/superres.hpp \
		/usr/local/include/opencv2/superres/optical_flow.hpp \
		/usr/local/include/opencv2/video.hpp \
		/usr/local/include/opencv2/video/tracking.hpp \
		/usr/local/include/opencv2/video/background_segm.hpp \
		/usr/local/include/opencv2/video/tracking_c.h \
		/usr/local/include/opencv2/videostab.hpp \
		/usr/local/include/opencv2/videostab/stabilizer.hpp \
		/usr/local/include/opencv2/videostab/global_motion.hpp \
		/usr/local/include/opencv2/videostab/optical_flow.hpp \
		/usr/local/include/opencv2/videostab/motion_core.hpp \
		/usr/local/include/opencv2/videostab/outlier_rejection.hpp \
		/usr/local/include/opencv2/videostab/motion_stabilizing.hpp \
		/usr/local/include/opencv2/videostab/frame_source.hpp \
		/usr/local/include/opencv2/videostab/log.hpp \
		/usr/local/include/opencv2/videostab/inpainting.hpp \
		/usr/local/include/opencv2/videostab/fast_marching.hpp \
		/usr/local/include/opencv2/videostab/fast_marching_inl.hpp \
		/usr/local/include/opencv2/videostab/deblurring.hpp \
		/usr/local/include/opencv2/videostab/wobble_suppression.hpp \
		/usr/local/include/opencv2/videostab/ring_buffer.hpp \
		/usr/local/include/opencv2/viz.hpp \
		/usr/local/include/opencv2/viz/types.hpp \
		/usr/local/include/opencv2/viz/widgets.hpp \
		/usr/local/include/opencv2/viz/viz3d.hpp \
		/usr/local/include/opencv2/viz/vizcore.hpp \
		/usr/local/include/opencv2/core/core.hpp \
		/usr/local/include/opencv2/highgui/highgui.hpp \
		/usr/local/include/opencv2/imgproc/imgproc.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dector.o dector.cpp

socketclient.o: socketclient.cpp socketclient.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtNetwork/QTcpSocket \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtNetwork/qtcpsocket.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtNetwork/qabstractsocket.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qiodevice.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qglobal.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qconfig.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qfeatures.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qsystemdetection.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qprocessordetection.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qcompilerdetection.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qtypeinfo.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qtypetraits.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qisenum.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qsysinfo.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qlogging.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qflags.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qatomic.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qbasicatomic.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qgenericatomic.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qatomic_cxx11.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qatomic_gcc.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qatomic_msvc.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qatomic_armv7.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qatomic_armv6.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qatomic_armv5.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qatomic_ia64.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qatomic_x86.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qatomic_unix.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qglobalstatic.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qmutex.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qnumeric.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qversiontagging.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qobject.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qobjectdefs.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qnamespace.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qstring.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qchar.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qbytearray.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qrefcount.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qarraydata.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qstringbuilder.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qlist.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qalgorithms.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qiterator.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qhashfunctions.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qpair.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qbytearraylist.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qstringlist.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qregexp.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qstringmatcher.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qcoreevent.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qscopedpointer.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qmetatype.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qvarlengtharray.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qcontainerfwd.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qobject_impl.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qdebug.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qhash.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qmap.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qtextstream.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qlocale.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qvariant.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qshareddata.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qvector.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qpoint.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qset.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qcontiguouscache.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtNetwork/QtNetwork \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtNetwork/QtNetworkDepends \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/QtCore \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/QtCoreDepends \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qabstractanimation.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qanimationgroup.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qparallelanimationgroup.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qpauseanimation.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qpropertyanimation.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qvariantanimation.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qeasingcurve.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qsequentialanimationgroup.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qtextcodec.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qendian.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qlibraryinfo.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qdatetime.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qbuffer.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qdatastream.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qdir.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qfileinfo.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qfile.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qfiledevice.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qdiriterator.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qfileselector.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/QObject \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/QStringList \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qfilesystemwatcher.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qlockfile.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qloggingcategory.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qprocess.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qresource.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qsavefile.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qsettings.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qstandardpaths.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qstorageinfo.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qtemporarydir.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/QScopedPointer \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qtemporaryfile.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qurl.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qurlquery.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qabstractitemmodel.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qabstractproxymodel.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qidentityproxymodel.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qitemselectionmodel.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qsortfilterproxymodel.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qstringlistmodel.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qjsonarray.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qjsonvalue.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qjsondocument.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qjsonobject.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qabstracteventdispatcher.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qeventloop.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qabstractnativeeventfilter.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qbasictimer.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qcoreapplication.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qmath.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qmetaobject.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qmimedata.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qobjectcleanuphandler.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qpointer.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qsharedpointer.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qsharedmemory.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qsignalmapper.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qsocketnotifier.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qsystemsemaphore.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qtimer.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qtranslator.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qwineventnotifier.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qmimedatabase.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qmimetype.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qfactoryinterface.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qlibrary.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qplugin.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qpluginloader.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/quuid.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qabstractstate.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qabstracttransition.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qeventtransition.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qfinalstate.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qhistorystate.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qsignaltransition.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qstate.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qstatemachine.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qexception.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qfuture.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qfutureinterface.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qrunnable.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qresultstore.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qfuturesynchronizer.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qfuturewatcher.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qreadwritelock.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qsemaphore.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qthread.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qthreadpool.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qthreadstorage.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qwaitcondition.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qarraydataops.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qarraydatapointer.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qbitarray.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qbytearraymatcher.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qcache.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qcollator.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qcommandlineoption.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qcommandlineparser.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qcryptographichash.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qelapsedtimer.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qline.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qlinkedlist.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qmargins.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qmessageauthenticationcode.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qqueue.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qrect.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qsize.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qregularexpression.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qscopedvaluerollback.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qstack.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qtextboundaryfinder.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qtimeline.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qtimezone.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qversionnumber.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qxmlstream.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qtcoreversion.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtNetwork/qabstractnetworkcache.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtNetwork/qnetworkrequest.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/QSharedDataPointer \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/QString \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/QUrl \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/QVariant \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtNetwork/qhttpmultipart.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/QByteArray \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/QIODevice \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtNetwork/QNetworkRequest \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtNetwork/qnetworkaccessmanager.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtNetwork/QSslConfiguration \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtNetwork/qsslconfiguration.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtNetwork/qsslsocket.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtNetwork/qsslerror.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtNetwork/qsslcertificate.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtNetwork/qssl.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/QFlags \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtNetwork/QSslPreSharedKeyAuthenticator \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtNetwork/qsslpresharedkeyauthenticator.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/QtGlobal \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/QMetaType \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtNetwork/qnetworkcookie.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/QList \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtNetwork/qnetworkcookiejar.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtNetwork/qnetworkdiskcache.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtNetwork/qnetworkreply.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtNetwork/QNetworkAccessManager \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtNetwork/qnetworkconfigmanager.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtNetwork/qnetworkconfiguration.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtNetwork/qnetworksession.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtNetwork/qnetworkinterface.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtNetwork/qhostaddress.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtNetwork/qauthenticator.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtNetwork/qdnslookup.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtNetwork/qhostinfo.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtNetwork/qnetworkproxy.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtNetwork/qlocalserver.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtNetwork/qlocalsocket.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtNetwork/qtcpserver.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtNetwork/qudpsocket.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtNetwork/qsslcertificateextension.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtNetwork/qsslcipher.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtNetwork/qsslellipticcurve.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/QHash \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtNetwork/qsslkey.h \
		/opt/Qt5.6.0/5.6/gcc_64/include/QtNetwork/qtnetworkversion.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o socketclient.o socketclient.cpp

moc_socketclient.o: moc_socketclient.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_socketclient.o moc_socketclient.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

